[build]
  base = "/"
  publish = "build/"
  command = "yarn run build"
  functions = "src/functions/"
  ignore = "git diff --quiet HEAD^ HEAD src/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Language = ["pt"]}
[[redirects]]
  from = "/*"
  to = "/index-es.html"
  status = 200
  conditions = {Language = ["en"]}
[[redirects]]
  from = "/*"
  to = "/index-en.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors https://www.facebook.com"
	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''
