[build]
  base = "/"
  publish = "build/"
  command = "make build"
  functions = "functions/"
  ignore = "git diff --quiet HEAD^ HEAD src/"
[build.environment]
  GO_IMPORT_PATH = "github.com/Squad-1-React-Codenation/Fashionista"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors https://www.facebook.com"
	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''
